### ISSUE TITLE
Attendance API - 출석하기, 취소하기 기능 

### ISSUE THREAD

**Issue by tjdxo1193** [zi-nye/up-lord-api#16]
Attendance API - 출석하기, 취소하기 기능 
출석하기, 취소하기를 한번에 List로 api 요청을 보내는 것이 
한번 UPDATE로 효율적으로 처리할 수 있을 거라고 보임.
Y(출석O) , N(출석X)

**Comment by Dev-Yesung** [comment]
회의를 통해 위와 같은 방식으로 처리하기로 했습니다. 이슈를 닫겠습니다!
